#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
logo_darkmode = "images/logo.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "320px"
logo_height = "164px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Vintage Wedding Cars Melbourne"
# navbar fixed to top
navbar_fixed = false
# theme-mode
theme_switcher = true
theme_default = "system" # available options [light/dark/system]
# Main Sections
mainSections = ["Cars"]
# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright
copyright = "| [Always Classic Cars](https://alwaysclassiccars.com.au/) | All Rights Reserved | Powered by [Bennell IT](https://www.bennellit.com.au)"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "get a quote"
link = "contact"

# search
[search]
enable = true
primary_color = "#121212"
include_sections = ["cars"]
show_image = true
show_description = true
show_tags = true
show_categories = false


# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Classic Cars ", "Vintage ", "Melbourne Biggest Vintage ", "Austin", "Rolls Royce", "Bentley", "Weddings", "Debutante Balls", "School Formals"]
description = "Melbourne’ Biggest Vintage and Classic Cars Collection Ranging from 1932 to 1975 "
author = "Stewart Bennell"
image = "images/marker.png"


# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################  "categories", 
[widgets]
sidebar = ["tags"]


# google map
[google_map]
enable = false
map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU" #AIzaSyCaGlA1U0fjMFZRti3LDrpgfGp715ek_XQ
map_latitude = "-37.824830"
map_longitude = "145.113730"
map_marker = "images/marker.png"

# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
